### ISSUE TITLE
Did you use only One picture for main training？？

### ISSUE THREAD

**Issue by Johnson-yue** [yongqyu/TCN#2]
Hi，It is me ,again. 
I want to confirm did you use only one __png__ picture for training? 
As you said,  ImageFolder() function was used in main training,  but if and only if  image_path contain **png**   Is it meaning  input a picture only??

**Comment by yongqyu** [comment]
Hi, Johnson.
In main training, the input is a single png image. And we also need a target image that is paired with the input.

In addition, through the name of the png file, we can know the typeface index and character index of the image. This is all you need to learn.
I hope this answer helps you, and if you do not understand, always ask.

Thank you.
