### ISSUE TITLE
Did you update your code with training Open dataset？

### ISSUE THREAD

**Issue by Johnson-yue** [yongqyu/TCN#3]
I train your code with my own dataset ， the private font dataset， but failed！！ I think I still not understand  how to make dataset format for training your code。

If you can use public dataset ， I think mybe easy to understand your code 。

Anyway， thank you for your share~~

**Comment by LeeJunHyun** [comment]
I think it works well for .png format. 
@Johnson-yue What is your data format?

**Comment by Johnson-yue** [comment]
@LeeJunHyun Yes， I know the .png format is work. But the information of png pictures is more importance!  I guess the train dataset have a lot of .png picture,  and every picture have three picture like : 

line 1 -  Font1_Character1 |  line2 - Font2_Charcater2  |  line 3 - Font2_Character2   and it's size should be [256*3, 256], 

 I'm not sure if that's the case.   And what is test dataset？？？ it is the same format ？？？

**Comment by yongqyu** [comment]
Every picture has only one ltter. The filename is 'font-idx_char-idx.png' for each character. Use the same dataset for pre-trainning, learning, and testing.

I recently updated my repository. Please check again.

**Comment by Johnson-yue** [comment]
I'm glad to see the update. I'll try it right away. Thank you.
